const {
  VITE_REACT_API_DOMAIN_URL,
  VITE_REACT_API_IP_URL,
  VITE_REACT_DEV_URL,
  VITE_REACT_STAGE,
  VITE_REACT_SECRET_KEY,
} = import.meta.env;
const url =
  VITE_REACT_STAGE === "DEV" ? VITE_REACT_DEV_URL : VITE_REACT_API_IP_URL;
// : VITE_REACT_API_DOMAIN_URL;
const stage = VITE_REACT_STAGE;
const key = VITE_REACT_SECRET_KEY;

export { url, stage, key };
